# Generated by Django 5.1.6 on 2025-02-12 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="base_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_by", models.CharField(max_length=50, null=True)),
                ("updated_by", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "base_model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transcriptions.base_model",
                    ),
                ),
                ("audio_id", models.CharField(max_length=50, unique=True)),
                ("audio_file", models.FileField(upload_to="")),
                ("file_size", models.PositiveIntegerField(null=True)),
                ("duration", models.FloatField(null=True)),
            ],
            bases=("transcriptions.base_model",),
        ),
        migrations.CreateModel(
            name="AudioFileChunk",
            fields=[
                (
                    "base_model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transcriptions.base_model",
                    ),
                ),
                ("chunk_file", models.FileField(upload_to="audio_chunks/")),
                ("duration", models.FloatField(null=True)),
                ("feature_text", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("not_sure", "Not Sure"),
                        ],
                        default="not_sure",
                        max_length=10,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sw", "Swahili"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=5,
                    ),
                ),
                ("is_evaluated", models.BooleanField(default=False)),
                ("eveluation_count", models.PositiveIntegerField(default=0)),
                ("trancribe_chunk", models.BooleanField(default=False)),
            ],
            bases=("transcriptions.base_model",),
        ),
        migrations.CreateModel(
            name="evaluation_results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("single_speaker", models.BooleanField(default=False)),
                ("sepeaker_overlap", models.BooleanField(default=False)),
                ("background_noise", models.BooleanField(default=False)),
                ("prolonged_silence", models.BooleanField(default=False)),
                ("background_noise_level", models.FloatField()),
                ("Not_Speech_Rate", models.BooleanField(default=False)),
                ("echo_noise", models.BooleanField(default=False)),
                ("is_evaluated", models.BooleanField(default=False)),
                ("is_evaluated_by", models.CharField(max_length=50, null=True)),
                ("evaluation_date", models.DateTimeField(null=True)),
                ("evaluation_notes", models.TextField(null=True)),
                (
                    "audiofilechunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_results",
                        to="transcriptions.audiofilechunk",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseRecord",
            fields=[
                (
                    "base_model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transcriptions.base_model",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("talk_time", models.TimeField()),
                ("case_id", models.CharField(max_length=20)),
                ("narrative", models.TextField()),
                ("plan", models.TextField()),
                ("main_category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("gbv", models.BooleanField()),
                (
                    "audio_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_record",
                        to="transcriptions.audiofile",
                    ),
                ),
            ],
            bases=("transcriptions.base_model",),
        ),
        migrations.CreateModel(
            name="evaluated_audio_file",
            fields=[
                (
                    "base_model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transcriptions.base_model",
                    ),
                ),
                ("is_evaluated", models.BooleanField(default=False)),
                ("is_evaluated_by", models.CharField(max_length=50, null=True)),
                ("evaluation_date", models.DateTimeField(null=True)),
                ("evaluation_notes", models.TextField(null=True)),
                ("evaluation_score", models.FloatField(null=True)),
                ("evaluation_status", models.CharField(max_length=50, null=True)),
                ("evaluation_result", models.CharField(max_length=50, null=True)),
                ("evaluation_result_score", models.FloatField(null=True)),
                (
                    "evaluation_result_status",
                    models.CharField(max_length=50, null=True),
                ),
                ("evaluation_result_notes", models.TextField(null=True)),
                (
                    "audio_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluated_audio_file",
                        to="transcriptions.audiofile",
                    ),
                ),
            ],
            bases=("transcriptions.base_model",),
        ),
        migrations.CreateModel(
            name="evaluation_record",
            fields=[
                (
                    "base_model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transcriptions.base_model",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("talk_time", models.TimeField()),
                ("case_id", models.CharField(max_length=20)),
                ("narrative", models.TextField()),
                ("plan", models.TextField()),
                ("main_category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("gbv", models.BooleanField()),
                ("true_transcription", models.TextField()),
                (
                    "audio_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_record",
                        to="transcriptions.audiofile",
                    ),
                ),
            ],
            bases=("transcriptions.base_model",),
        ),
    ]
